match x:
    case [a] | [b]: ...                    
    case [a] | []: ...                      
    case (x, y) | (x,): ...                 
    case [a, _] | [a, b]: ...               
    case (x, (y | z)): ...                  
    case [a] | [b] | [c]: ...   
