async class Foo: ...
async while test: ...
async x = 1
async async def foo(): ...
# TODO(dhruvmanila): Here, `match` is actually a Name token because
# of the soft keyword # transformer
async match test:
    case _: ...
