#:schema ../ty.schema.json
# Configuration overrides for the mypy primer run

# Enable off-by-default rules.
[rules]
division-by-zero = "warn"
possibly-missing-attribute = "warn"
possibly-missing-import = "warn"
possibly-unresolved-reference = "warn"
unsupported-dynamic-base = "warn"
