[[pools]]
name = "ruff"
paths = [
  "/crates/ruff/**",
  "/crates/ruff_linter/**",
]
reviewers = ["ntBre"]

[[pools]]
name = "ty-semantic"
paths = ["/crates/ty_python_core/**", "/crates/ty_python_semantic/**"]
reviewers = ["carljm", "charliermarsh", "sharkdp", "dcreager", "ibraheemdev", "oconnor663", "dhruvmanila"]

[[pools]]
name = "ty-module-resolver"
paths = ["/crates/ty_module_resolver/**", "/crates/ty_site_packages/**"]
reviewers = ["carljm", "MichaReiser"]

[[pools]]
name = "ty-infra"
paths = [
  "/crates/ruff_db/**",
  "/crates/ty_combine/**",
  "/crates/ty_project/**",
  "/crates/ty/**",
  "/crates/ty_benchmark/**",
  "/crates/ruff_benchmark/benches/ty*",
]
reviewers = ["carljm", "charliermarsh", "MichaReiser"]

[[pools]]
name = "ty-wasm"
paths = ["/crates/ty_wasm/**"]
reviewers = ["MichaReiser"]

[[pools]]
name = "ty-ide"
paths = ["/crates/ty_ide/**"]
reviewers = ["charliermarsh", "MichaReiser", "dhruvmanila"]

[[pools]]
name = "ty-server"
paths = ["/crates/ty_server/**"]
reviewers = ["charliermarsh", "MichaReiser", "dhruvmanila"]
