//! Parse the import-hook editable finder artifacts generated by setuptools v70.0.0 and later.
//!
//! This crate deliberately interprets only that emitted finder shape. It never executes `.pth`
//! startup code or finder modules. See `SETUPTOOLS_FINDER_HISTORY.md` for the compatibility
//! boundary and the older released formats we intentionally do not parse today.

use ruff_db::system::{System, SystemPath, SystemPathBuf};
use ruff_python_ast as ast;
use ruff_python_parser::parse_module;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Finder {
    site_packages: SystemPathBuf,
    mapping: Vec<Mapping>,
    namespaces: Vec<Namespace>,
}

impl Finder {
    pub fn site_packages(&self) -> &SystemPath {
        &self.site_packages
    }

    pub fn mapping(&self) -> &[Mapping] {
        &self.mapping
    }

    pub fn namespaces(&self) -> &[Namespace] {
        &self.namespaces
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Mapping {
    module: Box<str>,
    path: SystemPathBuf,
}

impl Mapping {
    pub fn module(&self) -> &str {
        &self.module
    }

    pub fn path(&self) -> &SystemPath {
        &self.path
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Namespace {
    module: Box<str>,
    paths: Vec<SystemPathBuf>,
}

impl Namespace {
    pub fn module(&self) -> &str {
        &self.module
    }

    pub fn paths(&self) -> &[SystemPathBuf] {
        &self.paths
    }
}

/// Return the generated finder module referenced by a setuptools v70.0.0+ `.pth` launcher line.
///
/// Setuptools v70.0.0 and later write:
///
/// ```python
/// import __editable___pkg_finder; __editable___pkg_finder.install()
/// ```
///
/// We recognize only that narrow generated shape, and only simple identifier-like module names so
/// the caller can safely turn the result into a sibling `*.py` path.
pub fn finder_module_from_pth_line(line: &str) -> Option<&str> {
    let line = line.trim_end();
    let rest = line
        .strip_prefix("import ")
        .or_else(|| line.strip_prefix("import\t"))?;
    let (module, install) = rest.split_once(';')?;
    let module = module.trim();
    let install = install.trim();

    if !is_generated_finder_module(module) || install != format!("{module}.install()") {
        return None;
    }

    Some(module)
}

/// Parse a setuptools v70.0.0+ generated finder module without executing it.
pub fn parse_finder(
    system: &dyn System,
    site_packages: &SystemPath,
    finder_path: &SystemPath,
) -> Option<Finder> {
    let contents = match system.read_to_string(finder_path) {
        Ok(contents) => contents,
        Err(error) => {
            tracing::warn!("Failed to read setuptools editable finder `{finder_path}`: {error}");
            return None;
        }
    };

    let parsed = match parse_module(&contents) {
        Ok(parsed) => parsed,
        Err(error) => {
            tracing::debug!("Skipping invalid setuptools editable finder `{finder_path}`: {error}");
            return None;
        }
    };

    let mut mapping = None;
    let mut namespaces = None;

    for statement in parsed.suite() {
        let ast::Stmt::AnnAssign(ast::StmtAnnAssign {
            target,
            value: Some(value),
            ..
        }) = statement
        else {
            continue;
        };
        let ast::Expr::Name(name) = &**target else {
            continue;
        };

        if name.id() == "MAPPING" {
            mapping = Some(parse_mapping(value, system)?);
        } else if name.id() == "NAMESPACES" {
            namespaces = Some(parse_namespaces(value, system)?);
        }
    }

    Some(Finder {
        site_packages: site_packages.to_path_buf(),
        mapping: mapping?,
        namespaces: namespaces?,
    })
}

fn parse_mapping(value: &ast::Expr, system: &dyn System) -> Option<Vec<Mapping>> {
    let ast::Expr::Dict(ast::ExprDict { items, .. }) = value else {
        return None;
    };

    items
        .iter()
        .map(|item| {
            let Some(ast::Expr::StringLiteral(module)) = item.key.as_ref() else {
                return None;
            };
            let ast::Expr::StringLiteral(path) = &item.value else {
                return None;
            };

            Some(Mapping {
                module: Box::from(module.value.to_str()),
                path: canonicalized_system_path(system, path.value.to_str()),
            })
        })
        .collect()
}

fn parse_namespaces(value: &ast::Expr, system: &dyn System) -> Option<Vec<Namespace>> {
    let ast::Expr::Dict(ast::ExprDict { items, .. }) = value else {
        return None;
    };

    items
        .iter()
        .map(|item| {
            let Some(ast::Expr::StringLiteral(module)) = item.key.as_ref() else {
                return None;
            };
            let ast::Expr::List(ast::ExprList { elts, .. }) = &item.value else {
                return None;
            };

            let paths = elts
                .iter()
                .map(|path| {
                    let ast::Expr::StringLiteral(path) = path else {
                        return None;
                    };
                    Some(canonicalized_system_path(system, path.value.to_str()))
                })
                .collect::<Option<Vec<_>>>()?;

            Some(Namespace {
                module: Box::from(module.value.to_str()),
                paths,
            })
        })
        .collect()
}

fn canonicalized_system_path(system: &dyn System, path: &str) -> SystemPathBuf {
    let path = SystemPathBuf::from(path);
    system.canonicalize_path(&path).unwrap_or(path)
}

fn is_generated_finder_module(module: &str) -> bool {
    module.starts_with("__editable___")
        && module.chars().enumerate().all(|(index, character)| {
            character == '_'
                || character.is_ascii_alphabetic()
                || (index > 0 && character.is_ascii_digit())
        })
}

#[cfg(test)]
mod tests {
    use super::finder_module_from_pth_line;

    #[test]
    fn recognizes_current_setuptools_pth_launcher() {
        assert_eq!(
            finder_module_from_pth_line(
                "import __editable___pkg_finder; __editable___pkg_finder.install()"
            ),
            Some("__editable___pkg_finder")
        );
    }

    #[test]
    fn rejects_non_generated_or_path_like_launchers() {
        assert_eq!(
            finder_module_from_pth_line("import pkg_finder; pkg_finder.install()"),
            None
        );
        assert_eq!(
            finder_module_from_pth_line(
                "import __editable___pkg/finder; __editable___pkg/finder.install()"
            ),
            None
        );
    }
}
