pub(crate) use backslashes::*;
pub(crate) use blank_after_summary::*;
pub(crate) use blank_before_after_class::*;
pub(crate) use blank_before_after_function::*;
pub(crate) use capitalized::*;
pub(crate) use ends_with_period::*;
pub(crate) use ends_with_punctuation::*;
pub(crate) use if_needed::*;
pub(crate) use indent::*;
pub(crate) use multi_line_summary_start::*;
pub(crate) use newline_after_last_paragraph::*;
pub(crate) use no_signature::*;
pub(crate) use no_surrounding_whitespace::*;
pub(crate) use non_imperative_mood::*;
pub(crate) use not_empty::*;
pub(crate) use not_missing::*;
pub(crate) use one_liner::*;
pub(crate) use sections::*;
pub(crate) use starts_with_this::*;
pub(crate) use triple_quotes::*;

mod backslashes;
mod blank_after_summary;
mod blank_before_after_class;
mod blank_before_after_function;
mod capitalized;
mod ends_with_period;
mod ends_with_punctuation;
mod if_needed;
mod indent;
mod multi_line_summary_start;
mod newline_after_last_paragraph;
mod no_signature;
mod no_surrounding_whitespace;
mod non_imperative_mood;
mod not_empty;
mod not_missing;
mod one_liner;
mod sections;
mod starts_with_this;
mod triple_quotes;
