use insta_cmd::assert_cmd_snapshot;

use crate::CliTest;

fn assert_contains_all(content: &str, needles: &[&str]) {
    for needle in needles {
        assert!(content.contains(needle), "missing `{needle}`");
    }
}

fn assert_contains_none(content: &str, needles: &[&str]) {
    for needle in needles {
        assert!(!content.contains(needle), "unexpected `{needle}`");
    }
}

fn assert_appears_before(content: &str, left: &str, right: &str) {
    let left = content
        .find(left)
        .unwrap_or_else(|| panic!("missing `{left}`"));
    let right = content
        .find(right)
        .unwrap_or_else(|| panic!("missing `{right}`"));
    assert!(left < right, "expected `{left}` to appear before `{right}`");
}

#[test]
fn generates_project_documentation() -> anyhow::Result<()> {
    let case = CliTest::with_files([
        (
            "pkg/__init__.py",
            r#"
            """Sample package.

            The package landing page should show this module documentation.

            For **fast** docs, see [helpers](pkg/helpers).
            Generated by script.amazon_polly.

            # Examples

            - Create a `Widget`.

            ```
            make_widget("example")
            ```
            """

            from typing import Any, Callable

            VALUE: int = 1
            """Value docs."""

            CONFIG = {
                "mode": "fast",
            }
            """Config docs."""

            type StringAlias = str

            class Widget:
                """A widget."""

                name: str
                """The widget name."""

                callback: Callable[[Any], str]
                RETRY_LIMIT = 5
                DEFAULT_LABEL = "widget"

                def __init__(self, name: str) -> None:
                    """Create a widget."""
                    self.name = name

                def render(self) -> str:
                    """Render the widget."""
                    return self.name

                def configure(self, primary_option: str, fallback_widget: Widget, *, enabled: bool = True) -> Widget:
                    """Configure the widget."""
                    return fallback_widget

            def make_widget(name: str) -> Widget:
                """Build a widget."""
                return Widget(name)
            "#,
        ),
        (
            "pkg/helpers.py",
            r#"
            """Helper functions."""

            def identity(value: object) -> object:
                """Return *value* unchanged."""
                return value
            "#,
        ),
        (
            "tests/test_pkg.py",
            r#"
            """Test suite docs should not be generated by default."""

            def test_widget() -> None:
                """Test helper docs."""
            "#,
        ),
    ])?;

    let output_root = case.root().join("target/doc");
    std::fs::create_dir_all(output_root.join("other"))?;
    std::fs::write(output_root.join("other/index.html"), "Other library docs.")?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let output = output_root.join("project");
    let library_index = std::fs::read_to_string(output_root.join("index.html"))?;
    assert_contains_all(
        &library_index,
        &[
            "<h1 id=\"page-title\"><a class=\"pm\"",
            ">Libraries</h1>",
            "<a href=\"other/index.html\">other</a>",
            "<a href=\"project/index.html\">project</a>",
        ],
    );

    let project_index = std::fs::read_to_string(output.join("index.html"))?;
    assert_contains_all(
        &project_index,
        &[
            "Project <span>project</span>",
            "<h2><a href=\"",
            ">project</a></h2>",
            "<h1 id=\"page-title\"><a class=\"pm\" href=\"#page-title\" aria-label=\"Permalink to this page\">§</a>Project <span>project</span></h1>",
            "pkg/index.html",
            "<a href=\"../index.html\">Libraries</a>",
            "tydoc-search",
            "<div class=\"search topbar-search\">",
            "Library Documentation",
            "<h2 id=\"library-documentation\"><a class=\"pm\" href=\"#library-documentation\"",
            "<strong>fast</strong>",
            "<h2>Examples</h2>",
        ],
    );
    assert_contains_none(&project_index, &["search-index.js"]);

    let module = std::fs::read_to_string(output.join("pkg/index.html"))?;
    assert_contains_all(
        &module,
        &[
            "Module <span>pkg</span>",
            "<h2><a href=\"",
            ">pkg</a></h2>",
            "Sample package.",
            "For <strong>fast</strong> docs, see <a href=\"pkg/helpers\">helpers</a>.",
            "Generated by script.amazon_polly.",
            "<h2>Examples</h2>",
            "<li>Create a <code>Widget</code>.",
            "make_widget(<span class=\"str\">&quot;example&quot;</span>)",
            ">helpers</a></dt><dd>",
            "src/pkg/__init__.py.html#L1",
            "class.Widget.html",
            "#fn.make_widget",
            "<section id=\"fn.make_widget\" class=\"itm\">",
            "-&gt; <a class=\"ty\" href=\"class.Widget.html\">Widget</a>",
            "id=\"var.VALUE\"",
            "<dt id=\"var.VALUE\" class=\"ve\"><a class=\"pm vpm\" href=\"#var.VALUE\" aria-label=\"Permalink to var VALUE\">§</a><code class=\"vs var\">VALUE: <a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#int\">int</a> = <span class=\"num\">1</span></code>",
            "Value docs.",
            "<dt id=\"var.CONFIG\" class=\"ve\"><a class=\"pm vpm\" href=\"#var.CONFIG\" aria-label=\"Permalink to var CONFIG\">§</a><code class=\"vs var\">CONFIG: <a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#dict\">dict</a>[<a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#str\">str</a>, <a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#str\">str</a>]</code>",
            "Config docs.",
            "<dt id=\"type.StringAlias\" class=\"ve\"><a class=\"pm vpm\" href=\"#type.StringAlias\" aria-label=\"Permalink to type StringAlias\">§</a><code class=\"vs type\">StringAlias = <a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#str\">str</a></code>",
        ],
    );
    assert_contains_none(&module, &["<h2>Module <a href=\"", "CONFIG = { ... }"]);

    let class = std::fs::read_to_string(output.join("pkg/class.Widget.html"))?;
    assert_contains_all(
        &class,
        &[
            "Class <span>Widget</span>",
            "src/pkg/__init__.py.html#L",
            "<h3><a href=\"#attributes\">Attributes</a></h3><ul class=\"block item-list\">",
            "<li><a href=\"#attr.name\">name</a>",
            "<h3><a href=\"#methods\">Methods</a></h3><ul class=\"block item-list\"><li><a href=\"#method.__init__\">__init__</a>",
            "<div class=\"iss ats\">",
            "<section id=\"attr.name\" class=\"itm\">",
            "<a class=\"pm\" href=\"#attr.name\" aria-label=\"Permalink\">§</a>",
            "<code class=\"asg var sig\">name:",
            "<section id=\"attr.callback\" class=\"itm\">",
            "<section id=\"attr.RETRY_LIMIT\" class=\"itm\">",
            "RETRY_LIMIT = <span class=\"num\">5</span>",
            "<section id=\"attr.DEFAULT_LABEL\" class=\"itm\">",
            "DEFAULT_LABEL = <span class=\"str\">&quot;widget&quot;</span>",
            "id=\"attr.name\"",
            "<a class=\"bi\" href=\"https://docs.python.org/3/library/typing.html#typing.Callable\">Callable</a>",
            "<a class=\"bi\" href=\"https://docs.python.org/3/library/typing.html#typing.Any\">Any</a>",
            "<section id=\"method.render\" class=\"itm\">",
            "id=\"method.render\"",
            "<span class=\"kw\">def</span> __init__",
            "<span class=\"kw\">def</span> render",
            "<div class=\"det col open\"><div class=\"sum\"><button class=\"tog itog\"",
            "<code class=\"sig\"><span class=\"kw\">def</span> render",
            "<code class=\"sig sgx\"><span class=\"kw\">def</span> configure(",
            "<code class=\"sig sgc\"><span class=\"kw\">def</span> configure(...) -&gt; <a class=\"ty\" href=\"class.Widget.html\">Widget</a></code>",
            "fallback_widget: <a class=\"ty\" href=\"class.Widget.html\">Widget</a>,",
            "<a class=\"src\" href=\"../src/pkg/__init__.py.html#L",
            "<a class=\"src heading-source\" href=\"../src/pkg/__init__.py.html#L",
            "<a class=\"pm\" href=\"#method.render\" aria-label=\"Permalink\">§</a>",
            "The widget name.",
        ],
    );
    assert_contains_none(
        &class,
        &[
            "<div class=\"source\">Source:",
            "<pre class=\"item-signature\">",
            "<h3><a href=\"#method.render\">render</a></h3>",
            "<summary class=\"item-summary\">",
            "<details class=\"item-details\"",
            ": ...</code></summary>",
        ],
    );

    assert!(!output.join("pkg/fn.make_widget.html").exists());

    let helpers = std::fs::read_to_string(output.join("pkg/helpers/index.html"))?;
    assert_contains_all(
        &helpers,
        &[
            "Module <span>helpers</span>",
            "<a href=\"../index.html\">pkg</a>",
            "Return <em>value</em> unchanged.",
        ],
    );
    assert!(!output.join("tests/test_pkg/index.html").exists());

    let all_items = std::fs::read_to_string(output.join("all.html"))?;
    assert_contains_all(&all_items, &["Variables", "pkg.VALUE", "#var.VALUE"]);

    let search_index = std::fs::read_to_string(output_root.join("search-index.js"))?;
    assert_contains_all(
        &search_index,
        &[
            "window.tyDocSearchIndex",
            "[\"class\",\"Widget\",\"pkg.Widget\"",
            "\"pkg.Widget.render\"",
            "[\"source\",\"pkg/__init__.py\",\"pkg\"",
            "src/pkg/__init__.py.html",
        ],
    );

    let search_script = std::fs::read_to_string(output_root.join("static.files/tydoc.js"))?;
    assert_contains_all(
        &search_script,
        &[
            "tyDocSearchIndex",
            "search-index.js",
            "No results",
            "name.textContent = item[NAME];",
            "path.className = \"search-result-path\";",
        ],
    );
    let source = std::fs::read_to_string(output.join("src/pkg/__init__.py.html"))?;
    assert_contains_all(
        &source,
        &[
            "Source <span>pkg/__init__.py</span>",
            "id=\"L",
            "<span class=\"kw\">class</span> Widget:",
        ],
    );

    Ok(())
}

#[test]
fn members_are_grouped_and_sorted_by_name() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        ZETA = 1
        type TextAlias = str
        ALPHA = 2

        class Zebra:
            zeta: int
            alpha: int

            def zeta_method(self) -> None:
                pass

            def alpha_method(self) -> None:
                pass

        class Alpha:
            pass

        def zeta() -> None:
            pass

        def alpha() -> None:
            pass
        "#,
    )])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let output = case.root().join("target/doc/project");
    let module = std::fs::read_to_string(output.join("pkg/index.html"))?;
    assert_appears_before(&module, ">Alpha</a></dt>", ">Zebra</a></dt>");
    assert_appears_before(&module, "id=\"fn.alpha\"", "id=\"fn.zeta\"");
    assert_appears_before(&module, "id=\"var.ALPHA\"", "id=\"var.ZETA\"");
    assert_appears_before(&module, "id=\"var.ZETA\"", "id=\"type.TextAlias\"");

    let class = std::fs::read_to_string(output.join("pkg/class.Zebra.html"))?;
    assert_appears_before(&class, "id=\"attr.alpha\"", "id=\"attr.zeta\"");
    assert_appears_before(
        &class,
        "id=\"method.alpha_method\"",
        "id=\"method.zeta_method\"",
    );

    Ok(())
}

#[test]
fn markdown_docblocks_preserve_non_breaking_indents_and_hard_breaks() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        def field() -> None:
            """Describe a field.

            Args:
                default: Default value if the field is not set.
                default_factory: A callable to generate the default value.
                    This may use already validated data.
            """
        "#,
    )])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let module = std::fs::read_to_string(case.root().join("target/doc/project/pkg/index.html"))?;
    assert_contains_all(
        &module,
        &[
            "<p>Describe a field.</p>",
            "<p>Args:<br>&nbsp;&nbsp;&nbsp;&nbsp;default: Default value if the field is not set.<br>&nbsp;&nbsp;&nbsp;&nbsp;default_factory: A callable to generate the default value.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This may use already validated data.</p>",
        ],
    );
    assert_contains_none(&module, &["&amp;nbsp;"]);

    Ok(())
}

#[test]
fn explicit_paths_can_document_tests() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "tests/test_pkg.py",
        r#"
        """Test suite docs."""

        def test_widget() -> None:
            """Test helper docs."""
        "#,
    )])?;

    let output_dir = case.root().join("docs");
    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("tests").arg("--color").arg("never").arg("--output-dir").arg(&output_dir), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/docs/project/index.html

    ----- stderr -----
    ");

    assert!(
        output_dir
            .join("project/tests/test_pkg/index.html")
            .exists()
    );

    Ok(())
}

#[test]
fn dataclass_fields_hide_defaults() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        from dataclasses import dataclass, field

        @dataclass
        class Config:
            items: list[str] = field(default_factory=list)
        "#,
    )])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let class =
        std::fs::read_to_string(case.root().join("target/doc/project/pkg/class.Config.html"))?;
    assert_contains_all(
        &class,
        &[
            "id=\"attr.items\"",
            "items: <a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#list\">list</a>[<a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#str\">str</a>]",
        ],
    );
    assert_contains_none(&class, &["default_factory"]);

    Ok(())
}

#[test]
fn enum_members_render_in_the_class_signature() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        from enum import StrEnum

        class Unit(StrEnum):
            """Unit docs."""

            SECONDS = "s"
            MINUTES = "min"
        "#,
    )])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let output_root = case.root().join("target/doc");
    let class = std::fs::read_to_string(output_root.join("project/pkg/class.Unit.html"))?;
    assert_contains_all(
        &class,
        &[
            "<pre class=\"signature enum-signature\"><code>",
            "<span id=\"member.SECONDS\" class=\"enum-member-line\">    SECONDS = <span class=\"str\">&quot;s&quot;</span></span>",
            "<span id=\"member.MINUTES\" class=\"enum-member-line\">    MINUTES = <span class=\"str\">&quot;min&quot;</span></span>",
        ],
    );
    assert_contains_none(&class, &["<h2 id=\"attributes\">", "#attr.SECONDS"]);

    let search_index = std::fs::read_to_string(output_root.join("search-index.js"))?;
    assert_contains_all(
        &search_index,
        &[
            "class.Unit.html#member.SECONDS",
            "[\"enum member\",\"SECONDS\"",
        ],
    );

    Ok(())
}

#[test]
fn source_highlights_f_string_expressions_separately() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        VALUE = 4
        OTHER = 2
        MESSAGE = f"{VALUE}.{OTHER + 1}"
        "#,
    )])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let source = std::fs::read_to_string(
        case.root()
            .join("target/doc/project/src/pkg/__init__.py.html"),
    )?;
    assert_contains_all(
        &source,
        &[
            "MESSAGE = <span class=\"str\">f&quot;</span>{VALUE}<span class=\"str\">.</span>{OTHER + <span class=\"num\">1</span>}<span class=\"str\">&quot;</span>",
        ],
    );
    assert_contains_none(
        &source,
        &["<span class=\"str\">f&quot;{VALUE}.{OTHER + 1}&quot;</span>"],
    );

    Ok(())
}

#[test]
fn stdlib_signature_links_follow_resolved_definitions() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        import dataclasses
        from typing import Any as TypingAny
        from unresolved_dependency import ExternalType

        class Any:
            """Local class that shadows typing.Any."""

        class Holder:
            object: object

        def local(value: Any) -> Any:
            """Use the local class."""

        def external(value: TypingAny) -> TypingAny:
            """Use the imported stdlib type alias."""

        def unresolved(value: ExternalType) -> ExternalType:
            """Do not invent docs.python.org links for unresolved external types."""

        def uses_path(value: int = dataclasses.field(default=1)) -> None:
            """Use a dotted stdlib path in the signature."""
        "#,
    )])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let output = case.root().join("target/doc/project/pkg");
    let module = std::fs::read_to_string(output.join("index.html"))?;
    assert_contains_all(
        &module,
        &[
            "value: <a class=\"ty\"",
            "class.Any.html\">Any</a>",
            "<a class=\"bi\" href=\"https://docs.python.org/3/library/typing.html#typing.Any\">TypingAny</a>",
            "value: ExternalType",
            "<a class=\"bi\" href=\"https://docs.python.org/3/library/dataclasses.html\">dataclasses</a>.<a class=\"bi\" href=\"https://docs.python.org/3/library/dataclasses.html#dataclasses.field\">field</a>",
        ],
    );
    assert_contains_none(
        &module,
        &[
            "typing.html#typing.Any\">Any</a>",
            "ty_extensions.html#ty_extensions.ExternalType",
        ],
    );

    let holder = std::fs::read_to_string(output.join("class.Holder.html"))?;
    assert_contains_all(
        &holder,
        &[
            "<a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#object\">object</a>",
        ],
    );
    assert!(!output.join("fn.local.html").exists());
    assert!(!output.join("fn.external.html").exists());
    assert!(!output.join("fn.unresolved.html").exists());
    assert!(!output.join("fn.uses_path.html").exists());

    Ok(())
}

#[test]
fn source_links_for_decorated_items_target_the_definition_name() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        def decorator(item):
            return item

        @decorator
        def decorated() -> None:
            """Decorated function."""

        @decorator
        class Decorated:
            """Decorated class."""
        "#,
    )])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let output = case.root().join("target/doc/project/pkg");
    let module = std::fs::read_to_string(output.join("index.html"))?;
    assert_contains_all(&module, &["src/pkg/__init__.py.html#L6"]);
    assert_contains_none(&module, &["src/pkg/__init__.py.html#L5"]);
    assert!(!output.join("fn.decorated.html").exists());

    let class = std::fs::read_to_string(output.join("class.Decorated.html"))?;
    assert_contains_all(&class, &["src/pkg/__init__.py.html#L10"]);
    assert_contains_none(&class, &["src/pkg/__init__.py.html#L9"]);

    Ok(())
}

#[test]
fn empty_module_source_links_avoid_missing_line_anchors() -> anyhow::Result<()> {
    let case = CliTest::with_files([("pkg/__init__.py", "")])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let output = case.root().join("target/doc/project");
    let module = std::fs::read_to_string(output.join("pkg/index.html"))?;
    assert_contains_all(&module, &["src/pkg/__init__.py.html"]);
    assert_contains_none(&module, &["src/pkg/__init__.py.html#L1"]);

    let source = std::fs::read_to_string(output.join("src/pkg/__init__.py.html"))?;
    assert_contains_none(&source, &["id=\"L1\""]);

    Ok(())
}

#[test]
fn class_member_overloads_are_grouped() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        from typing import overload

        class Parser:
            @overload
            def parse(self, value: str) -> str:
                """Parse text."""
                ...

            @overload
            def parse(self, value: int) -> int:
                """Parse numbers."""
                ...

            def parse(self, value: object) -> object:
                """Parse a value."""
                return value
        "#,
    )])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let output_root = case.root().join("target/doc");
    let class = std::fs::read_to_string(output_root.join("project/pkg/class.Parser.html"))?;
    assert_contains_all(
        &class,
        &[
            "id=\"method.parse\"",
            "<span class=\"overload-count\">2 overloads</span>",
            "<div class=\"overload-list\"><h3>Overload signatures</h3>",
            "<div class=\"overload-entry\"><div class=\"overload-signature\">",
            "<code class=\"sig\"><span class=\"kw\">def</span> parse(self, value: <a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#str\">str</a>) -&gt; <a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#str\">str</a></code>",
            "<code class=\"sig\"><span class=\"kw\">def</span> parse(self, value: <a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#int\">int</a>) -&gt; <a class=\"bi\" href=\"https://docs.python.org/3/library/functions.html#int\">int</a></code>",
            "Parse text.",
            "Parse numbers.",
            "<a class=\"pm\" href=\"#method.parse\" aria-label=\"Permalink\">§</a>",
            "Parse a value.",
        ],
    );
    assert_contains_none(&class, &["method.parse-1"]);
    assert_eq!(
        class
            .matches("<li><a href=\"#method.parse\">parse</a>")
            .count(),
        1
    );
    assert_eq!(class.matches("id=\"method.parse\"").count(), 1);
    let search_index = std::fs::read_to_string(output_root.join("search-index.js"))?;
    assert_contains_all(&search_index, &["class.Parser.html#method.parse"]);
    assert_contains_none(&search_index, &["class.Parser.html#method.parse-1"]);

    Ok(())
}

#[test]
fn class_pages_show_documented_inheritance() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        class GrandBase:
            """Grand base docs."""

            root_attr: str
            """Root attribute."""

            def root(self) -> str:
                """Root method."""
                return ""

        class Base(GrandBase):
            """Base docs."""

            inherited_attr: int
            """Inherited attribute."""

            shared_attr: str
            """Base shared attribute."""

            def inherited(self) -> str:
                """Inherited method."""
                return ""

            @property
            def inherited_property(self) -> str:
                """Inherited property."""
                return ""

            @inherited_property.setter
            def inherited_property(self, value: str) -> None:
                pass

            def overridden(self) -> int:
                """Base method."""
                return 1

        class Child(Base):
            """Child docs."""

            root_attr: bytes

            shared_attr: int

            def root(self) -> str:
                return ""

            def overridden(self) -> int:
                return 2

        "#,
    )])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let class =
        std::fs::read_to_string(case.root().join("target/doc/project/pkg/class.Child.html"))?;
    assert_contains_all(
        &class,
        &[
            "<h2 id=\"inherited\"><a class=\"pm\" href=\"#inherited\"",
            "<section id=\"inherited.0\" class=\"ig col open\"><div class=\"isum\"><button class=\"tog ht\" aria-label=\"Toggle inherited members from Base\" aria-expanded=\"true\"></button><a class=\"pm\" href=\"#inherited.0\" aria-label=\"Permalink to inherited members from Base\">§</a><span class=\"inherited-title\">Inherited from <a class=\"class ibl\" href=\"class.Base.html\">Base</a></span></div><div class=\"dc\"><h3 class=\"ish\">Attributes</h3><div class=\"iss ats\">",
            "id=\"inherited.0.m.0\" class=\"itm\"",
            "<a class=\"pm\" href=\"#inherited.0.m.0\" aria-label=\"Permalink\">§</a>",
            "<a class=\"src\" href=\"../src/pkg/__init__.py.html#L",
            "id=\"method.overridden\" class=\"itm\"",
            "id=\"method.root\" class=\"itm\"",
            "Base method.",
            "Root method.",
            "<h3 class=\"ish\">Methods</h3><div class=\"iss\">",
            "id=\"inherited.0.a.0\" class=\"itm\"",
            "<section id=\"inherited.0.a.0\" class=\"itm\"><div class=\"sum sst\">",
            "<a class=\"pm\" href=\"#inherited.0.a.0\" aria-label=\"Permalink\">§</a>",
            "inherited_property",
            "id=\"attr.shared_attr\" class=\"itm\"",
            "id=\"attr.root_attr\" class=\"itm\"",
            "Base shared attribute.",
            "Root attribute.",
            "<a href=\"#inherited\">Inherited</a>",
            "<li><a href=\"#inherited.0\">Base</a>",
            "<li><a href=\"#inherited.1\">GrandBase</a>",
        ],
    );
    assert_contains_none(
        &class,
        &[
            "Base Classes",
            "<h2 id=\"attributes\">",
            "<h2 id=\"methods\">",
            "<h3><a href=\"#methods\">Methods</a></h3>",
            "<h2 id=\"inherited-methods\">",
            "<h2 id=\"inherited-attributes\">",
            "Overrides <a href=\"class.Base.html#method.overridden\">Base.overridden</a>",
            "Overrides <a href=\"class.GrandBase.html#method.root\">GrandBase.root</a>",
            "Overrides <a href=\"class.Base.html#attr.shared_attr\">Base.shared_attr</a>",
            "Overrides <a href=\"class.GrandBase.html#attr.root_attr\">GrandBase.root_attr</a>",
            "<summary class=\"isum\">",
            "aria-controls=",
            "<details id=\"inherited-from.",
            "id=\"inherited-method.pkg.Base.inherited_property\"",
        ],
    );

    Ok(())
}

#[test]
fn default_docs_prefer_project_package_root() -> anyhow::Result<()> {
    let case = CliTest::with_files([
        (
            "project/__init__.py",
            r#"
            """Project package docs."""
            "#,
        ),
        (
            "script/__init__.py",
            r#"
            """Repository tooling docs."""
            "#,
        ),
    ])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let output = case.root().join("target/doc/project");
    assert!(output.join("project/index.html").exists());
    assert!(!output.join("script/index.html").exists());

    Ok(())
}

#[test]
fn emits_parse_warnings_but_still_generates_docs() -> anyhow::Result<()> {
    let case = CliTest::with_files([("bad.py", "def broken(")])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
    warning[invalid-syntax]: unexpected EOF while parsing
    --> bad.py:1:1
     |
     |

    warning: `project` (doc) generated 1 warning
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    assert!(case.root().join("target/doc/project/index.html").exists());

    Ok(())
}

#[test]
fn sibling_stub_modules_take_precedence() -> anyhow::Result<()> {
    let case = CliTest::with_files([
        ("pkg/__init__.py", ""),
        (
            "pkg/api.py",
            r#"
            """Runtime module docs."""

            class RuntimeOnly:
                """Runtime class."""
            "#,
        ),
        (
            "pkg/api.pyi",
            r#"
            """Stub module docs."""

            class StubOnly:
                """Stub class."""
            "#,
        ),
    ])?;

    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never"), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/target/doc/project/index.html

    ----- stderr -----
    ");

    let module =
        std::fs::read_to_string(case.root().join("target/doc/project/pkg/api/index.html"))?;
    assert_contains_all(
        &module,
        &["Stub module docs.", "StubOnly", "src/pkg/api.pyi.html#L1"],
    );
    assert_contains_none(
        &module,
        &["Runtime module docs.", "RuntimeOnly", "src/pkg/api.py.html"],
    );

    Ok(())
}

#[test]
fn private_items_are_opt_in() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        def public() -> None:
            """Public function."""

        def _private() -> None:
            """Private function."""
        "#,
    )])?;

    let default_output = case.root().join("default-docs");
    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never").arg("--output-dir").arg(&default_output), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/default-docs/project/index.html

    ----- stderr -----
    ");

    let module = std::fs::read_to_string(default_output.join("project/pkg/index.html"))?;
    assert_contains_all(&module, &["public"]);
    assert_contains_none(&module, &["_private"]);

    let private_output = case.root().join("private-docs");
    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never").arg("--document-private-items").arg("--output-dir").arg(&private_output), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/private-docs/project/index.html

    ----- stderr -----
    ");

    let module = std::fs::read_to_string(private_output.join("project/pkg/index.html"))?;
    assert_contains_all(&module, &["_private"]);

    Ok(())
}

#[test]
fn all_items_follow_ty_public_exports() -> anyhow::Result<()> {
    let case = CliTest::with_files([(
        "pkg/__init__.py",
        r#"
        __all__ = ["Documented", "listed", "VALUE"]

        class Documented:
            """Listed class."""

        class Hidden:
            """Hidden class."""

        def listed() -> None:
            """Listed function."""

        def hidden() -> None:
            """Hidden function."""

        VALUE = 1
        HIDDEN_VALUE = 2
        "#,
    )])?;

    let output_dir = case.root().join("docs");
    assert_cmd_snapshot!(case.ty_command().arg("doc").arg("--color").arg("never").arg("--output-dir").arg(&output_dir), @"
    success: true
    exit_code: 0
    ----- stdout -----
     Documenting project (<temp_dir>/)
        Finished documentation in 0.000s
       Generated <temp_dir>/docs/project/index.html

    ----- stderr -----
    ");

    let all_items = std::fs::read_to_string(output_dir.join("project/all.html"))?;
    assert_contains_all(&all_items, &["pkg.Documented", "pkg.listed", "pkg.VALUE"]);
    assert_contains_none(
        &all_items,
        &["pkg.Hidden", "pkg.hidden", "pkg.HIDDEN_VALUE"],
    );

    Ok(())
}
