//! Render method manifests as Rust source targeting the OGAR Core.
//!
//! [`render`] turns the per-class [`ClassManifest`]s into a Rust source string:
//! one `pub const <CLASS>_METHODS: &[MethodSig]` per class, naming
//! `lance_graph_contract::codegen_manifest::MethodSig`. It is **emit-text-only**:
//! the output names the Core type as text but the crate never depends on
//! lance-graph (the text is type-checked later, in the consumer repo, after the
//! `MethodSig` EXTEND-CORE lands). Every file carries the
//! `PARITY: UNRUN (operator-blocked: leptonica)` marker so a green codegen run
//! is never mistaken for the byte-parity FINDING.
//!
//! The render is deterministic (classes sorted by name, methods by
//! `(name, params, is_const)`) and ASCII-clean. Strings are escaped, so a
//! parameter type containing a comma (`std::map<int, int>`) is emitted as one
//! quoted array element, never split.
//!
//! # Frankenstein guard
//!
//! Methods on the hand-curated deny-list (intrusive / state-leaking leaves the
//! harvest cannot distinguish by predicate -- e.g. `UNICHARSET::id_to_unichar_ext`
//! fragment expansion) are annotated with a `// HAND-PORT` comment, marking them
//! for a hand-port rather than a mechanical adapter at body-generation time. The
//! signature still appears in the manifest; the annotation is the routing
//! signal, since the harvest carries no intrusiveness predicate (a queued
//! harvester GAP).

use std::fmt::Write as _;

use crate::manifest::ClassManifest;

/// Hand-port deny-list: `(class-suffix, method, reason)`. The harvest cannot
/// distinguish a pure table-lookup leaf from a state-leaking one (no
/// intrusiveness predicate), so this is necessarily hand-curated. Matched by
/// `class.ends_with(suffix) && method == name`.
const HAND_PORT: &[(&str, &str, &str)] = &[
    (
        "UNICHARSET",
        "id_to_unichar_ext",
        "fragment expansion leaks state",
    ),
    (
        "UNICHARSET",
        "CleanupString",
        "normalization with internal state",
    ),
];

/// Render the method manifests as Rust source. See the module docs.
#[must_use]
pub fn render(manifests: &[ClassManifest]) -> String {
    // Writing to a `String` via `fmt::Write` is infallible; the `Result` is
    // discarded deliberately.
    let mut out = String::new();
    let _ = writeln!(out, "//! @generated by ruff_cpp_codegen -- DO NOT EDIT.");
    let _ = writeln!(out, "//! PARITY: UNRUN (operator-blocked: leptonica)");
    let _ = writeln!(out, "//!");
    let _ = writeln!(
        out,
        "//! C++ method-resolution manifests projected from the ruff_cpp_spo harvest."
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "use lance_graph_contract::codegen_manifest::MethodSig;"
    );

    let mut classes = manifests.to_vec();
    classes.sort_by(|a, b| a.class.cmp(&b.class));
    for manifest in &classes {
        let mut methods = manifest.methods.clone();
        methods.sort_by(|a, b| {
            (a.name.as_str(), &a.params, a.is_const).cmp(&(b.name.as_str(), &b.params, b.is_const))
        });
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "/// Methods of `{}` (from has_function + signature predicates).",
            manifest.class
        );
        let _ = writeln!(
            out,
            "pub const {}_METHODS: &[MethodSig] = &[",
            const_ident(&manifest.class)
        );
        for method in &methods {
            if let Some(reason) = is_hand_port(&manifest.class, &method.name) {
                let _ = writeln!(
                    out,
                    "    // HAND-PORT ({reason}): route to hand-port, not a mechanical adapter."
                );
            }
            let params = method
                .params
                .iter()
                .map(|p| format!("\"{}\"", escape(p)))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                out,
                "    MethodSig {{ name: \"{}\", params: &[{params}], ret: {}, \
                 is_const: {}, is_static: {}, overrides: {} }},",
                escape(&method.name),
                opt(method.ret.as_deref()),
                method.is_const,
                method.is_static,
                opt(method.overrides.as_deref()),
            );
        }
        let _ = writeln!(out, "];");
    }
    out
}

/// Render an `Option<&str>` as a Rust `Option` literal with the string escaped.
fn opt(value: Option<&str>) -> String {
    match value {
        Some(s) => format!("Some(\"{}\")", escape(s)),
        None => "None".to_string(),
    }
}

/// Escape a string for a Rust double-quoted literal (`\` and `"`).
fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// A valid Rust `SCREAMING_SNAKE` const-name fragment from a class name
/// (`tesseract::UNICHARSET` -> `TESSERACT_UNICHARSET`). Runs of non-alphanumeric
/// characters collapse to a single `_`; a leading digit is prefixed with `_`.
fn const_ident(class: &str) -> String {
    let mut id = String::with_capacity(class.len());
    let mut prev_underscore = false;
    for c in class.chars() {
        if c.is_ascii_alphanumeric() {
            id.push(c.to_ascii_uppercase());
            prev_underscore = false;
        } else if !prev_underscore {
            id.push('_');
            prev_underscore = true;
        }
    }
    if id.starts_with(|c: char| c.is_ascii_digit()) {
        id.insert(0, '_');
    }
    id
}

/// The hand-port reason for `(class, method)`, if denied.
fn is_hand_port(class: &str, method: &str) -> Option<&'static str> {
    HAND_PORT.iter().find_map(|(suffix, name, reason)| {
        (class.ends_with(suffix) && method == *name).then_some(*reason)
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::{ClassManifest, MethodSig};

    fn sample() -> Vec<ClassManifest> {
        vec![ClassManifest {
            class: "tesseract::UNICHARSET".to_string(),
            methods: vec![
                MethodSig {
                    name: "unichar_to_id".to_string(),
                    params: vec!["const char *".to_string()],
                    ret: Some("UNICHAR_ID".to_string()),
                    is_const: true,
                    is_static: false,
                    overrides: None,
                },
                MethodSig {
                    name: "id_to_unichar_ext".to_string(),
                    params: vec!["UNICHAR_ID".to_string()],
                    ret: Some("const char *".to_string()),
                    is_const: true,
                    is_static: false,
                    overrides: None,
                },
            ],
        }]
    }

    #[test]
    fn render_carries_parity_marker() {
        assert!(render(&sample()).contains("PARITY: UNRUN (operator-blocked: leptonica)"));
    }

    #[test]
    fn render_is_deterministic() {
        assert_eq!(render(&sample()), render(&sample()));
    }

    #[test]
    fn render_emits_every_method_and_names_core_type() {
        let s = render(&sample());
        assert!(s.contains("use lance_graph_contract::codegen_manifest::MethodSig;"));
        assert_eq!(
            s.matches("MethodSig {").count(),
            2,
            "one MethodSig literal per method"
        );
        assert!(s.contains("name: \"unichar_to_id\""));
        assert!(s.contains("pub const TESSERACT_UNICHARSET_METHODS: &[MethodSig]"));
    }

    #[test]
    fn render_flags_hand_port_denylist() {
        assert!(
            render(&sample()).contains("HAND-PORT (fragment expansion leaks state)"),
            "id_to_unichar_ext must be flagged for hand-port"
        );
    }

    /// A comma-bearing templated param is one quoted array element, never split
    /// on `,` (the baton-auditor's P1(a), now on the render side).
    #[test]
    fn render_quotes_comma_bearing_params() {
        let m = vec![ClassManifest {
            class: "Cache".to_string(),
            methods: vec![MethodSig {
                name: "merge".to_string(),
                params: vec!["std::map<int, int>".to_string(), "int".to_string()],
                ret: None,
                is_const: false,
                is_static: false,
                overrides: None,
            }],
        }];
        assert!(render(&m).contains("params: &[\"std::map<int, int>\", \"int\"]"));
    }
}
