use super::{InnerIntersectionBuilder, IntersectionBuilder};
use crate::Db;
use crate::types::Type;
use crate::types::UnionType;
use crate::types::tuple::{FixedLengthTuple, TupleSpec, TupleSpecBuilder, TupleType};
use crate::types::visitor::any_over_type;
use rustc_hash::FxHashSet;

/// Maximum number of tuple alternatives generated by indexed-protocol complements.
const MAX_INDEXED_PROTOCOL_COMPLEMENT_ALTERNATIVES: usize = 64;

/// Maximum total number of tuple elements copied into generated alternatives.
const MAX_INDEXED_PROTOCOL_COMPLEMENT_ELEMENTS: usize = 4_096;

/// Return whether tuple or protocol elements can be refined set-theoretically.
///
/// Dynamic types can be hidden behind aliases, so checking only the top-level types is insufficient.
fn all_elements_are_static(db: &dyn Db, elements: &[Type<'_>]) -> bool {
    elements
        .iter()
        .all(|element| !any_over_type(db, *element, true, |ty| ty.is_dynamic()))
}

/// Build an intersection used while simplifying indexed-protocol complements.
///
/// This can simplify ordinary intersections, but must leave nested indexed-protocol complements
/// symbolic so that the outer fixed-point pass remains in control.
fn build_indexed_protocol_simplification_intersection<'db>(
    db: &'db dyn Db,
    positives: impl IntoIterator<Item = Type<'db>>,
    negatives: impl IntoIterator<Item = Type<'db>>,
) -> Type<'db> {
    let mut builder = IntersectionBuilder::new(db).positive_elements(positives);
    for negative in negatives {
        builder = builder.add_negative(negative);
    }
    build_without_indexed_protocol_simplification(builder)
}

/// Build an intersection, including finite indexed-protocol simplification.
pub(super) fn build(builder: IntersectionBuilder<'_>) -> Type<'_> {
    build_without_indexed_protocol_simplification(builder.simplify_indexed_protocol_negatives())
}

/// Build without re-entering indexed-protocol simplification.
///
/// Nested builds leave indexed-protocol complements symbolic so that the outer fixed-point
/// iteration remains in control.
fn build_without_indexed_protocol_simplification(builder: IntersectionBuilder<'_>) -> Type<'_> {
    UnionType::from_elements(
        builder.db,
        builder
            .intersections
            .into_iter()
            .map(|inner| inner.build(builder.db)),
    )
}

/// Result of subtracting one finite indexed protocol from an exact tuple.
enum TupleProtocolComplement<'db> {
    /// The tuple is already disjoint from the protocol, so the complement adds no constraint.
    Redundant,
    /// Every tuple value satisfies the protocol, so its complement eliminates the branch.
    Eliminated,
    /// Each entry identifies a tuple position and the element type that violates the protocol.
    Alternatives(Vec<(usize, Type<'db>)>),
}

/// A synthesized protocol and its decoded element constraint for each exact index.
struct IndexedProtocolConstraint<'db> {
    protocol: Type<'db>,
    elements: Box<[Type<'db>]>,
}

/// The combined exact-tuple view of all tuple positives in one intersection branch.
///
/// `positive_indices` records which original positives must be replaced when the combined tuple is
/// refined or expanded.
struct StaticTupleIntersection<'db> {
    positive_indices: Vec<usize>,
    tuple: TupleSpec<'db>,
}

/// A preflighted replacement of one intersection branch with exact-tuple alternatives.
///
/// Materialization removes `handled_protocols` and the tuple positives represented by
/// `positive_indices`, then inserts one tuple positive for each element vector.
struct IndexedProtocolExpansion<'db> {
    handled_protocols: Vec<Type<'db>>,
    positive_indices: Vec<usize>,
    alternatives: Vec<Vec<Type<'db>>>,
}

/// Refine a tuple specialization using finite indexed constraints from a protocol.
///
/// Returns `None` when `ty` is not a tuple specialization, `Some(Never)` when the tuple shape is
/// disjoint from the protocol, and the refined tuple type otherwise.
///
/// This intentionally assumes that tuple subclasses preserve the relationship between iteration
/// and indexing provided by the builtin `tuple` class. A tuple subclass can override `__iter__` so
/// that a sequence pattern observes different element types than inherited indexing does, making
/// this refinement unsound for that subclass. We accept this limitation to retain precise
/// narrowing for ordinary tuple annotations.
fn refine_tuple_with_indexed_protocol<'db>(
    db: &'db dyn Db,
    ty: Type<'db>,
    protocol_elements: &[Type<'db>],
) -> Option<Type<'db>> {
    if !all_elements_are_static(db, protocol_elements) {
        return None;
    }

    let Type::NominalInstance(instance) = ty else {
        return None;
    };

    let tuple = instance.own_tuple_spec(db)?;
    if !all_elements_are_static(db, tuple.all_elements()) {
        return None;
    }

    let protocol_tuple = TupleSpec::heterogeneous(protocol_elements.iter().copied());
    let Some(refined) = TupleSpecBuilder::from(tuple.as_ref()).intersect(db, &protocol_tuple)
    else {
        return Some(Type::Never);
    };

    Some(Type::tuple(TupleType::new(db, &refined.build())))
}

/// Internalize a finite indexed protocol's element constraints into an exact tuple type.
///
/// For example:
///
/// ```python
/// def narrow(value: tuple[int | str, int | str]) -> None:
///     match value:
///         case [_, str()]:
///             reveal_type(value)  # tuple[int | str, str]
/// ```
pub(super) fn refine_tuple_protocol_intersection<'db>(
    db: &'db dyn Db,
    left: Type<'db>,
    right: Type<'db>,
) -> Option<Type<'db>> {
    let ((Type::ProtocolInstance(protocol), tuple) | (tuple, Type::ProtocolInstance(protocol))) =
        (left, right)
    else {
        return None;
    };
    let indexed = protocol.finite_indexed_constraint(db)?;
    refine_tuple_with_indexed_protocol(db, tuple, &indexed)
}

/// Analyze subtraction of finite indexed constraints from a fixed-length tuple type.
///
/// A complement with one unresolved position can be represented by refining that tuple element.
/// Complements with multiple unresolved positions require a union with one alternative per
/// position. Returns an error before constructing more than `max_alternatives` changes.
fn tuple_protocol_complement<'db>(
    db: &'db dyn Db,
    tuple: &FixedLengthTuple<Type<'db>>,
    protocol_elements: &[Type<'db>],
    max_alternatives: usize,
) -> Result<TupleProtocolComplement<'db>, ()> {
    if tuple.len() != protocol_elements.len() {
        return Ok(TupleProtocolComplement::Redundant);
    }

    let mut alternatives = Vec::new();
    for (index, (element, protocol_element)) in tuple
        .all_elements()
        .iter()
        .zip(protocol_elements)
        .enumerate()
    {
        if element.is_disjoint_from(db, *protocol_element) {
            return Ok(TupleProtocolComplement::Redundant);
        }
        if element.is_subtype_of(db, *protocol_element) {
            continue;
        }

        let remaining_element =
            build_indexed_protocol_simplification_intersection(db, [*element], [*protocol_element]);
        if remaining_element.is_never() {
            continue;
        }
        if alternatives.len() == max_alternatives {
            return Err(());
        }
        alternatives.push((index, remaining_element));
    }

    Ok(if alternatives.is_empty() {
        TupleProtocolComplement::Eliminated
    } else {
        TupleProtocolComplement::Alternatives(alternatives)
    })
}

impl<'db> IntersectionBuilder<'db> {
    /// Simplify finite indexed-protocol complements against exact tuple constraints.
    ///
    /// Unit clauses are propagated to a fixed point before ambiguous complements are expanded.
    /// Expansion is all-or-nothing across the builder: if the aggregate alternative or copied
    /// element budget is exceeded, ambiguous complements remain symbolic while propagated
    /// refinements are preserved.
    fn simplify_indexed_protocol_negatives(mut self) -> Self {
        let protocols = self.indexed_protocol_constraints();
        if protocols.is_empty() {
            return self;
        }

        let db = self.db;
        self.intersections = self
            .intersections
            .into_iter()
            .filter_map(|inner| inner.simplify_indexed_protocol_negatives(db, &protocols))
            .collect();

        let Ok(expansions) = self
            .intersections
            .iter()
            .map(|inner| inner.indexed_protocol_expansion(db, &protocols))
            .collect::<Result<Vec<_>, ()>>()
        else {
            return self;
        };

        let mut total_alternatives = 0usize;
        let mut total_elements = 0usize;
        for expansion in &expansions {
            total_alternatives = total_alternatives.saturating_add(
                expansion
                    .as_ref()
                    .map_or(1, |expansion| expansion.alternatives.len()),
            );
            total_elements =
                total_elements.saturating_add(expansion.as_ref().map_or(0, |expansion| {
                    expansion.alternatives.iter().map(Vec::len).sum()
                }));
            if total_alternatives > MAX_INDEXED_PROTOCOL_COMPLEMENT_ALTERNATIVES
                || total_elements > MAX_INDEXED_PROTOCOL_COMPLEMENT_ELEMENTS
            {
                return self;
            }
        }

        self.intersections = self
            .intersections
            .into_iter()
            .zip(expansions)
            .flat_map(|(inner, expansion)| match expansion {
                Some(expansion) => inner.materialize_indexed_protocol_expansion(db, expansion),
                None => vec![inner],
            })
            .collect();
        self
    }

    /// Collect the static finite indexed protocols used as negatives in any branch.
    ///
    /// Constraints are deduplicated and sorted by their displayed element types so fixed-point
    /// propagation and bounded expansion do not depend on insertion order.
    fn indexed_protocol_constraints(&self) -> Vec<IndexedProtocolConstraint<'db>> {
        let mut seen_protocols = FxHashSet::default();
        let mut constraints = Vec::new();

        for negative in self
            .intersections
            .iter()
            .flat_map(|inner| inner.negative.iter())
        {
            let Type::ProtocolInstance(protocol) = negative else {
                continue;
            };
            if !seen_protocols.insert(*negative) {
                continue;
            }
            let Some(elements) = protocol.finite_indexed_constraint(self.db) else {
                continue;
            };
            if !all_elements_are_static(self.db, &elements) {
                continue;
            }
            constraints.push(IndexedProtocolConstraint {
                protocol: *negative,
                elements,
            });
        }

        constraints.sort_by_cached_key(|constraint| {
            constraint
                .elements
                .iter()
                .map(|element| element.display(self.db).to_string())
                .collect::<Box<[_]>>()
        });
        constraints
    }
}

impl<'db> InnerIntersectionBuilder<'db> {
    /// Intersect every static exact-tuple positive in this branch.
    ///
    /// The returned indices identify the positives represented by the combined tuple so callers
    /// can replace them without discarding unrelated positive constraints.
    fn static_tuple_intersection(
        &self,
        db: &'db dyn Db,
    ) -> Result<Option<StaticTupleIntersection<'db>>, ()> {
        let mut positive_indices = Vec::new();
        let mut intersection: Option<TupleSpecBuilder<'db>> = None;

        for (positive_index, positive) in self.positive.iter().enumerate() {
            let Type::NominalInstance(instance) = positive else {
                continue;
            };
            let Some(tuple) = instance.own_tuple_spec(db) else {
                continue;
            };
            if !all_elements_are_static(db, tuple.all_elements()) {
                continue;
            }

            positive_indices.push(positive_index);
            intersection = Some(match intersection {
                Some(intersection) => intersection.intersect(db, tuple.as_ref()).ok_or(())?,
                None => TupleSpecBuilder::from(tuple.as_ref()),
            });
        }

        let Some(intersection) = intersection else {
            return Ok(None);
        };
        let intersection = intersection.build();
        if let TupleSpec::Fixed(tuple) = &intersection
            && tuple.all_elements().iter().any(Type::is_never)
        {
            return Err(());
        }
        Ok(Some(StaticTupleIntersection {
            positive_indices,
            tuple: intersection,
        }))
    }

    /// Propagate unambiguous indexed-protocol complements to a fixed point within one branch.
    ///
    /// A complement with one unresolved tuple position refines that element directly. Redundant
    /// complements are removed, an eliminated branch returns `None`, and complements requiring a
    /// union remain for the bounded expansion phase.
    fn simplify_indexed_protocol_negatives(
        mut self,
        db: &'db dyn Db,
        protocols: &[IndexedProtocolConstraint<'db>],
    ) -> Option<Self> {
        'fixed_point: loop {
            let intersection = match self.static_tuple_intersection(db) {
                Ok(Some(intersection)) => intersection,
                Ok(None) => return Some(self),
                Err(()) => return None,
            };
            let TupleSpec::Fixed(tuple) = &intersection.tuple else {
                return Some(self);
            };

            for constraint in protocols {
                if !self.negative.contains(&constraint.protocol) {
                    continue;
                }

                match tuple_protocol_complement(db, tuple, &constraint.elements, 2) {
                    Err(()) => continue,
                    Ok(TupleProtocolComplement::Redundant) => {
                        self.negative.swap_remove(&constraint.protocol);
                    }
                    Ok(TupleProtocolComplement::Eliminated) => return None,
                    Ok(TupleProtocolComplement::Alternatives(alternatives)) => {
                        let [(index, remaining_element)] = alternatives.as_slice() else {
                            continue;
                        };
                        let mut elements = tuple.all_elements().to_vec();
                        elements[*index] = *remaining_element;
                        for positive_index in intersection.positive_indices.into_iter().rev() {
                            self.positive.swap_remove_index(positive_index);
                        }
                        self.add_positive(db, Type::heterogeneous_tuple(db, elements));
                        if self.positive.contains(&Type::Never) {
                            return None;
                        }
                        self.negative.swap_remove(&constraint.protocol);
                        continue 'fixed_point;
                    }
                }
            }

            return Some(self);
        }
    }

    /// Preflight bounded expansion of the branch's remaining ambiguous tuple complements.
    ///
    /// This computes tuple element vectors without mutating the branch. Returning an error causes
    /// the outer builder to retain all ambiguous complements symbolically.
    fn indexed_protocol_expansion(
        &self,
        db: &'db dyn Db,
        protocols: &[IndexedProtocolConstraint<'db>],
    ) -> Result<Option<IndexedProtocolExpansion<'db>>, ()> {
        let Ok(Some(intersection)) = self.static_tuple_intersection(db) else {
            return Ok(None);
        };
        let TupleSpec::Fixed(tuple) = &intersection.tuple else {
            return Ok(None);
        };

        let mut handled_protocols = Vec::new();
        let mut alternatives = vec![tuple.all_elements().to_vec()];

        for constraint in protocols {
            if !self.negative.contains(&constraint.protocol) {
                continue;
            }
            let Ok(TupleProtocolComplement::Alternatives(tuple_alternatives)) =
                tuple_protocol_complement(
                    db,
                    tuple,
                    &constraint.elements,
                    MAX_INDEXED_PROTOCOL_COMPLEMENT_ALTERNATIVES,
                )
            else {
                continue;
            };
            if tuple_alternatives.len() < 2 {
                continue;
            }

            let mut expanded = Vec::new();
            let mut seen = FxHashSet::default();
            for elements in &alternatives {
                for (index, remaining_element) in &tuple_alternatives {
                    let mut elements = elements.clone();
                    let element = build_indexed_protocol_simplification_intersection(
                        db,
                        [elements[*index], *remaining_element],
                        [],
                    );
                    if element.is_never() {
                        continue;
                    }
                    elements[*index] = element;
                    if !seen.insert(elements.clone()) {
                        continue;
                    }
                    if expanded.len() == MAX_INDEXED_PROTOCOL_COMPLEMENT_ALTERNATIVES
                        || expanded
                            .len()
                            .saturating_add(1)
                            .saturating_mul(elements.len())
                            > MAX_INDEXED_PROTOCOL_COMPLEMENT_ELEMENTS
                    {
                        return Err(());
                    }
                    expanded.push(elements);
                }
            }

            handled_protocols.push(constraint.protocol);
            alternatives = expanded;
            if alternatives.is_empty() {
                break;
            }
        }

        if handled_protocols.is_empty() {
            return Ok(None);
        }
        Ok(Some(IndexedProtocolExpansion {
            handled_protocols,
            positive_indices: intersection.positive_indices,
            alternatives,
        }))
    }

    /// Apply a preflighted expansion without repeating complement analysis.
    ///
    /// Each generated branch retains unrelated positive and negative constraints. Alternatives
    /// that become uninhabited after reinsertion are discarded.
    fn materialize_indexed_protocol_expansion(
        mut self,
        db: &'db dyn Db,
        expansion: IndexedProtocolExpansion<'db>,
    ) -> Vec<Self> {
        for protocol in &expansion.handled_protocols {
            self.negative.swap_remove(protocol);
        }
        for positive_index in expansion.positive_indices.iter().rev() {
            self.positive.swap_remove_index(*positive_index);
        }

        let mut alternatives = Vec::with_capacity(expansion.alternatives.len());
        for elements in expansion.alternatives {
            let mut alternative = self.clone();
            alternative.add_positive(db, Type::heterogeneous_tuple(db, elements));
            if !alternative.positive.contains(&Type::Never) {
                alternatives.push(alternative);
            }
        }
        alternatives
    }
}
