use crate::Db;
use itertools::Itertools;

use crate::ProgramEnvironment;
use crate::types::enums::enum_member_literals;
use crate::types::tuple::Tuple;
use crate::types::{CycleDetector, IntersectionType, KnownClass, Type};

/// Maximum number of alternatives generated by expanding one argument's elements.
///
/// See: [pyright's `maxSingleOverloadArgTypeExpansionCount`][pyright]
///
/// [pyright]: https://github.com/microsoft/pyright/blob/5a325e4874e775436671eed65ad696787a1ef74b/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L570
const MAX_ELEMENT_EXPANSION: usize = 64;

/// Expands a type into its possible subtypes, if applicable.
///
/// Returns [`None`] if the type cannot be expanded.
pub(crate) fn expand_type<'db>(
    db: &'db dyn Db,
    env: &ProgramEnvironment<'db>,
    ty: Type<'db>,
) -> Option<Vec<Type<'db>>> {
    TypeExpander {
        db,
        env,
        visitor: CycleDetector::new(None),
    }
    .expand(ty)
}

/// Expands a sequence of element types, bounding the size of their Cartesian product.
pub(crate) fn expand_elements<'db>(
    db: &'db dyn Db,
    env: &ProgramEnvironment<'db>,
    elements: impl IntoIterator<Item = Type<'db>>,
) -> Option<Vec<Vec<Type<'db>>>> {
    TypeExpander {
        db,
        env,
        visitor: CycleDetector::new(None),
    }
    .expand_elements(elements)
}

/// Expand recursive aliases once per active specialization. A back-edge remains a tuple
/// element so argument expansion does not enumerate an infinite recursive unfolding.
struct TypeExpander<'a, 'db> {
    db: &'db dyn Db,
    env: &'a ProgramEnvironment<'db>,
    visitor: CycleDetector<'db, (), Type<'db>, Option<Vec<Type<'db>>>, 3>,
}

impl<'db> TypeExpander<'_, 'db> {
    fn expand_elements(
        &self,
        elements: impl IntoIterator<Item = Type<'db>>,
    ) -> Option<Vec<Vec<Type<'db>>>> {
        // Compute the product size before enumerating alternatives: a 37-element sequence of
        // two-element unions would otherwise allocate 2^37 combinations.
        let per_element: Vec<_> = elements
            .into_iter()
            .map(|element| self.expand(element).unwrap_or_else(|| vec![element]))
            .collect();
        let product_size = per_element
            .iter()
            .try_fold(1usize, |acc, alternatives| {
                acc.checked_mul(alternatives.len())
            })
            .unwrap_or(usize::MAX);
        if product_size <= 1 || product_size > MAX_ELEMENT_EXPANSION {
            return None;
        }
        Some(per_element.into_iter().multi_cartesian_product().collect())
    }

    fn expand(&self, ty: Type<'db>) -> Option<Vec<Type<'db>>> {
        let db = self.db;
        let env = self.env;
        match ty {
            Type::EnumComplement(complement) => Some(complement.remaining_literal_types(db, env)),
            Type::Intersection(intersection) => intersection.finite_alternatives(db, env),
            Type::NominalInstance(instance) => {
                let class = instance.class(db, env);

                if class.is_known(db, KnownClass::Bool) {
                    return Some(vec![Type::bool_literal(true), Type::bool_literal(false)]);
                }

                // If the class is a fixed-length tuple subtype, we expand it to its elements.
                if let Some(spec) = instance.tuple_spec(db, env) {
                    return match &*spec {
                        Tuple::Fixed(fixed_length_tuple) => self
                            .expand_elements(fixed_length_tuple.iter_all_elements())
                            .map(|alternatives| {
                                alternatives
                                    .into_iter()
                                    .map(|types| {
                                        let expanded = Type::heterogeneous_tuple(db, env, types);
                                        if instance.own_tuple_spec(db).is_some() {
                                            expanded
                                        } else {
                                            // The element types describe only the tuple base. Keep
                                            // the subclass identity in every expanded alternative.
                                            IntersectionType::from_two_elements(
                                                db, env, ty, expanded,
                                            )
                                        }
                                    })
                                    .collect()
                            }),
                        Tuple::Variable(_) => None,
                    };
                }

                if let Some(enum_members) = enum_member_literals(db, class.class_literal(db), None)
                {
                    return Some(enum_members.collect());
                }

                None
            }
            Type::Union(union) => Some(
                union
                    .elements(db)
                    .iter()
                    .flat_map(|element| match element {
                        Type::EnumComplement(complement) => {
                            complement.remaining_literal_types(db, env)
                        }
                        Type::Intersection(intersection) => intersection
                            .finite_alternatives(db, env)
                            .unwrap_or_else(|| vec![*element]),
                        _ => vec![*element],
                    })
                    .collect(),
            ),
            // For type aliases, expand the underlying value type.
            Type::TypeAlias(alias) => self
                .visitor
                .visit(db, ty, || self.expand(alias.value_type(db))),
            Type::Recursive(recursive) => self.visitor.visit(db, ty, || {
                self.expand(recursive.unfold(db, env).into_unfolded()?)
            }),
            // We don't handle `type[A | B]` here because it's already stored in the expanded form
            // i.e., `type[A] | type[B]` which is handled by the `Type::Union` case.
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::db::tests::setup_db;
    use crate::types::tuple::TupleType;
    use crate::types::{KnownClass, Type, UnionType};

    use super::expand_type;

    #[test]
    fn expand_union_type() {
        let db = setup_db();
        let db = &db;
        let env = db.program_environment();
        let types = [
            KnownClass::Int.to_instance(db, &env),
            KnownClass::Str.to_instance(db, &env),
            KnownClass::Bytes.to_instance(db, &env),
        ];
        let union_type = UnionType::from_elements(db, &env, types);
        let expanded = expand_type(db, &env, union_type).unwrap();
        assert_eq!(expanded.len(), types.len());
        assert_eq!(expanded, types);
    }

    #[test]
    fn expand_bool_type() {
        let db = setup_db();
        let db = &db;
        let env = db.program_environment();
        let bool_instance = KnownClass::Bool.to_instance(db, &env);
        let expanded = expand_type(db, &env, bool_instance).unwrap();
        let expected_types = [Type::bool_literal(true), Type::bool_literal(false)];
        assert_eq!(expanded.len(), expected_types.len());
        assert_eq!(expanded, expected_types);
    }

    #[test]
    fn expand_tuple_type() {
        let db = setup_db();
        let db = &db;
        let env = db.program_environment();

        let int_ty = KnownClass::Int.to_instance(db, &env);
        let str_ty = KnownClass::Str.to_instance(db, &env);
        let bytes_ty = KnownClass::Bytes.to_instance(db, &env);
        let bool_ty = KnownClass::Bool.to_instance(db, &env);
        let true_ty = Type::bool_literal(true);
        let false_ty = Type::bool_literal(false);

        // Empty tuple
        let empty_tuple = Type::empty_tuple(db, &env);
        let expanded = expand_type(db, &env, empty_tuple);
        assert!(expanded.is_none());

        // None of the elements can be expanded.
        let tuple_type1 = Type::heterogeneous_tuple(db, &env, [int_ty, str_ty]);
        let expanded = expand_type(db, &env, tuple_type1);
        assert!(expanded.is_none());

        // All elements can be expanded.
        let tuple_type2 = Type::heterogeneous_tuple(
            db,
            &env,
            [
                bool_ty,
                UnionType::from_elements(db, &env, [int_ty, str_ty, bytes_ty]),
            ],
        );
        let expected_types = [
            Type::heterogeneous_tuple(db, &env, [true_ty, int_ty]),
            Type::heterogeneous_tuple(db, &env, [true_ty, str_ty]),
            Type::heterogeneous_tuple(db, &env, [true_ty, bytes_ty]),
            Type::heterogeneous_tuple(db, &env, [false_ty, int_ty]),
            Type::heterogeneous_tuple(db, &env, [false_ty, str_ty]),
            Type::heterogeneous_tuple(db, &env, [false_ty, bytes_ty]),
        ];
        let expanded = expand_type(db, &env, tuple_type2).unwrap();
        assert_eq!(expanded, expected_types);

        // Mixed set of elements where some can be expanded while others cannot be.
        let tuple_type3 = Type::heterogeneous_tuple(
            db,
            &env,
            [
                bool_ty,
                int_ty,
                UnionType::from_elements(db, &env, [str_ty, bytes_ty]),
                str_ty,
            ],
        );
        let expected_types = [
            Type::heterogeneous_tuple(db, &env, [true_ty, int_ty, str_ty, str_ty]),
            Type::heterogeneous_tuple(db, &env, [true_ty, int_ty, bytes_ty, str_ty]),
            Type::heterogeneous_tuple(db, &env, [false_ty, int_ty, str_ty, str_ty]),
            Type::heterogeneous_tuple(db, &env, [false_ty, int_ty, bytes_ty, str_ty]),
        ];
        let expanded = expand_type(db, &env, tuple_type3).unwrap();
        assert_eq!(expanded, expected_types);

        // Variable-length tuples are not expanded.
        let variable_length_tuple = Type::tuple(TupleType::mixed(
            db,
            &env,
            [bool_ty],
            int_ty,
            [
                UnionType::from_elements(db, &env, [str_ty, bytes_ty]),
                str_ty,
            ],
        ));
        let expanded = expand_type(db, &env, variable_length_tuple);
        assert!(expanded.is_none());
    }
}
