[package]
name = "ruff_unicode_names2_generator"
version = "0.0.14"
description = "This is an internal component crate of Ruff"
authors = { workspace = true }
edition = "2018"
rust-version = "1.65.0"
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = "MIT OR Apache-2.0"

[dependencies]
phf_codegen = { workspace = true }
# Preserve the RNG used by upstream's table generator.
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("timing"))'] }

[lints.rustdoc]
bare_urls = "allow"

[lib]
name = "unicode_names2_generator"
