// Allow unused underscore violations generated by the salsa macro
// TODO(micha): Contribute fix upstream
#![allow(clippy::used_underscore_binding)]

use std::hash::{Hash, Hasher};
use std::ops::Range;

use bitflags::bitflags;
use hashbrown::hash_map::RawEntryMut;
use rustc_hash::FxHasher;
use smallvec::SmallVec;

use ruff_db::vfs::VfsFile;
use ruff_index::{newtype_index, IndexVec};

use crate::name::Name;
use crate::red_knot::semantic_index::definition::Definition;
use crate::red_knot::semantic_index::{scopes_map, symbol_table, SymbolMap};
use crate::Db;

#[derive(Eq, PartialEq, Debug)]
pub struct Symbol {
    name: Name,
    flags: SymbolFlags,
    scope: FileScopeId,

    /// The nodes that define this symbol, in source order.
    definitions: SmallVec<[Definition; 4]>,
}

impl Symbol {
    fn new(name: Name, scope: FileScopeId, definition: Option<Definition>) -> Self {
        Self {
            name,
            scope,
            flags: SymbolFlags::empty(),
            definitions: definition.into_iter().collect(),
        }
    }

    fn push_definition(&mut self, definition: Definition) {
        self.definitions.push(definition);
    }

    fn insert_flags(&mut self, flags: SymbolFlags) {
        self.flags.insert(flags);
    }

    /// The symbol's name.
    pub fn name(&self) -> &Name {
        &self.name
    }

    /// The scope in which this symbol is defined.
    pub fn scope(&self) -> FileScopeId {
        self.scope
    }

    /// Is the symbol used in its containing scope?
    pub fn is_used(&self) -> bool {
        self.flags.contains(SymbolFlags::IS_USED)
    }

    /// Is the symbol defined in its containing scope?
    pub fn is_defined(&self) -> bool {
        self.flags.contains(SymbolFlags::IS_DEFINED)
    }

    pub fn definitions(&self) -> &[Definition] {
        &self.definitions
    }
}

bitflags! {
    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    pub(super) struct SymbolFlags: u8 {
        const IS_USED         = 1 << 0;
        const IS_DEFINED      = 1 << 1;
        /// TODO: This flag is not yet set by anything
        const MARKED_GLOBAL   = 1 << 2;
        /// TODO: This flag is not yet set by anything
        const MARKED_NONLOCAL = 1 << 3;
    }
}

/// ID that uniquely identifies a public symbol defined in a module's root scope.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub struct PublicSymbolId {
    scope: ScopeId,
    symbol: ScopeSymbolId,
}

impl PublicSymbolId {
    pub(crate) fn new(scope: ScopeId, symbol: ScopeSymbolId) -> Self {
        Self { scope, symbol }
    }

    pub fn scope(self) -> ScopeId {
        self.scope
    }

    pub(crate) fn scope_symbol(self) -> ScopeSymbolId {
        self.symbol
    }
}

impl From<PublicSymbolId> for ScopeSymbolId {
    fn from(val: PublicSymbolId) -> Self {
        val.scope_symbol()
    }
}

/// ID that uniquely identifies a symbol in a file.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub struct FileSymbolId {
    scope: FileScopeId,
    symbol: ScopeSymbolId,
}

impl FileSymbolId {
    pub(super) fn new(scope: FileScopeId, symbol: ScopeSymbolId) -> Self {
        Self { scope, symbol }
    }

    pub fn scope(self) -> FileScopeId {
        self.scope
    }

    pub(crate) fn symbol(self) -> ScopeSymbolId {
        self.symbol
    }
}

impl From<FileSymbolId> for ScopeSymbolId {
    fn from(val: FileSymbolId) -> Self {
        val.symbol()
    }
}

/// Symbol ID that uniquely identifies a symbol inside a [`Scope`].
#[newtype_index]
pub(crate) struct ScopeSymbolId;

/// Maps from the file specific [`FileScopeId`] to the global [`ScopeId`] that can be used as a Salsa query parameter.
///
/// The [`SemanticIndex`] uses [`FileScopeId`] on a per-file level to identify scopes
/// because they allow for more efficient storage of associated data
/// (use of an [`IndexVec`] keyed by [`FileScopeId`] over an [`FxHashMap`] keyed by [`ScopeId`]).
#[derive(Eq, PartialEq, Debug)]
pub(crate) struct ScopesMap {
    scopes: IndexVec<FileScopeId, ScopeId>,
}

impl ScopesMap {
    pub(super) fn new(scopes: IndexVec<FileScopeId, ScopeId>) -> Self {
        Self { scopes }
    }

    /// Gets the program-wide unique scope id for the given file specific `scope_id`.
    fn get(&self, scope_id: FileScopeId) -> ScopeId {
        self.scopes[scope_id]
    }
}

/// A cross-module identifier of a scope that can be used as a salsa query parameter.
#[salsa::tracked]
pub struct ScopeId {
    #[allow(clippy::used_underscore_binding)]
    pub file: VfsFile,
    pub scope_id: FileScopeId,
}

impl ScopeId {
    /// Resolves the symbol named `name` in this scope.
    pub fn symbol(self, db: &dyn Db, name: &str) -> Option<PublicSymbolId> {
        let symbol_table = symbol_table(db, self);
        let in_scope_id = symbol_table.symbol_id_by_name(name)?;

        Some(PublicSymbolId::new(self, in_scope_id))
    }
}

/// ID that uniquely identifies a scope inside of a module.
#[newtype_index]
pub struct FileScopeId;

impl FileScopeId {
    /// Returns the scope id of the Root scope.
    pub fn root() -> Self {
        FileScopeId::from_u32(0)
    }

    pub fn to_scope_id(self, db: &dyn Db, file: VfsFile) -> ScopeId {
        scopes_map(db, file).get(self)
    }
}

#[derive(Debug, Eq, PartialEq)]
pub struct Scope {
    pub(super) name: Name,
    pub(super) parent: Option<FileScopeId>,
    pub(super) definition: Option<Definition>,
    pub(super) defining_symbol: Option<FileSymbolId>,
    pub(super) kind: ScopeKind,
    pub(super) descendents: Range<FileScopeId>,
}

impl Scope {
    pub fn name(&self) -> &Name {
        &self.name
    }

    pub fn definition(&self) -> Option<Definition> {
        self.definition
    }

    pub fn defining_symbol(&self) -> Option<FileSymbolId> {
        self.defining_symbol
    }

    pub fn parent(self) -> Option<FileScopeId> {
        self.parent
    }

    pub fn kind(&self) -> ScopeKind {
        self.kind
    }
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ScopeKind {
    Module,
    Annotation,
    Class,
    Function,
}

/// Symbol table for a specific [`Scope`].
#[derive(Debug)]
pub struct SymbolTable {
    /// The symbols in this scope.
    symbols: IndexVec<ScopeSymbolId, Symbol>,

    /// The symbols indexed by name.
    symbols_by_name: SymbolMap,
}

impl SymbolTable {
    fn new() -> Self {
        Self {
            symbols: IndexVec::new(),
            symbols_by_name: SymbolMap::default(),
        }
    }

    fn shrink_to_fit(&mut self) {
        self.symbols.shrink_to_fit();
    }

    pub(crate) fn symbol(&self, symbol_id: impl Into<ScopeSymbolId>) -> &Symbol {
        &self.symbols[symbol_id.into()]
    }

    #[allow(unused)]
    pub(crate) fn symbol_ids(&self) -> impl Iterator<Item = ScopeSymbolId> {
        self.symbols.indices()
    }

    pub fn symbols(&self) -> impl Iterator<Item = &Symbol> {
        self.symbols.iter()
    }

    /// Returns the symbol named `name`.
    #[allow(unused)]
    pub(crate) fn symbol_by_name(&self, name: &str) -> Option<&Symbol> {
        let id = self.symbol_id_by_name(name)?;
        Some(self.symbol(id))
    }

    /// Returns the [`ScopeSymbolId`] of the symbol named `name`.
    pub(crate) fn symbol_id_by_name(&self, name: &str) -> Option<ScopeSymbolId> {
        let (id, ()) = self
            .symbols_by_name
            .raw_entry()
            .from_hash(Self::hash_name(name), |id| {
                self.symbol(*id).name().as_str() == name
            })?;

        Some(*id)
    }

    fn hash_name(name: &str) -> u64 {
        let mut hasher = FxHasher::default();
        name.hash(&mut hasher);
        hasher.finish()
    }
}

impl PartialEq for SymbolTable {
    fn eq(&self, other: &Self) -> bool {
        // We don't need to compare the symbols_by_name because the name is already captured in `Symbol`.
        self.symbols == other.symbols
    }
}

impl Eq for SymbolTable {}

#[derive(Debug)]
pub(super) struct SymbolTableBuilder {
    table: SymbolTable,
}

impl SymbolTableBuilder {
    pub(super) fn new() -> Self {
        Self {
            table: SymbolTable::new(),
        }
    }

    pub(super) fn add_or_update_symbol(
        &mut self,
        name: Name,
        scope: FileScopeId,
        flags: SymbolFlags,
        definition: Option<Definition>,
    ) -> ScopeSymbolId {
        let hash = SymbolTable::hash_name(&name);
        let entry = self
            .table
            .symbols_by_name
            .raw_entry_mut()
            .from_hash(hash, |id| self.table.symbols[*id].name() == &name);

        match entry {
            RawEntryMut::Occupied(entry) => {
                let symbol = &mut self.table.symbols[*entry.key()];
                symbol.insert_flags(flags);

                if let Some(definition) = definition {
                    symbol.push_definition(definition);
                }

                *entry.key()
            }
            RawEntryMut::Vacant(entry) => {
                let mut symbol = Symbol::new(name, scope, definition);
                symbol.insert_flags(flags);

                let id = self.table.symbols.push(symbol);
                entry.insert_with_hasher(hash, id, (), |id| {
                    SymbolTable::hash_name(self.table.symbols[*id].name().as_str())
                });
                id
            }
        }
    }

    pub(super) fn finish(mut self) -> SymbolTable {
        self.table.shrink_to_fit();
        self.table
    }
}
