name: "Validate PGO"

permissions: {}

on:
  pull_request:
    paths:
      - pyproject.toml
      - .github/workflows/build-binaries.yml
      - .github/workflows/pgo.yml
      - scripts/build_ruff_pgo.py

concurrency:
  group: pgo-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10
  PYTHON_VERSION: "3.13"

jobs:
  pgo:
    name: "PGO"
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-build') }}
    runs-on: depot-ubuntu-24.04-8
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: "Install LLVM profiling tools"
        run: rustup component add llvm-tools-preview
      - name: "Run PGO pipeline"
        run: python scripts/build_ruff_pgo.py --debug
