name: ty ecosystem-analyzer

permissions: {}

on:
  pull_request:
    paths:
      - "crates/ty*/**"
      - "!crates/ty_ide/**"
      - "!crates/ty_server/**"
      - "!crates/ty_test/**"
      - "!crates/ty_completion_eval/**"
      - "!crates/ty_wasm/**"
      - "crates/ruff_db"
      - "crates/ruff_python_ast"
      - "crates/ruff_python_parser"
      - ".github/workflows/ty-ecosystem-analyzer.yaml"
      - ".github/ty-ecosystem.toml"
      - "crates/ty_python_semantic/resources/primer/**"
      - "Cargo.lock"
      - "!**.md"
      - "!**.snap"
      # It's tempting to skip all Python files in every directory,
      # but changes to Python files in `ty_vendored` can affect the output of ecosystem analysis,
      # so we apply a narrow exemption for all files in the corpus directory instead.
      - "!crates/ty_python_semantic/resources/corpus/**"

concurrency:
  group: ty-ecosystem-analyzer-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1
  REF_NAME: ${{ github.ref_name }}

jobs:
  ty-ecosystem-analyzer:
    name: Compute diagnostic diff
    runs-on: ${{ github.repository == 'astral-sh/ruff' && 'depot-ubuntu-22.04-32' || 'ubuntu-latest' }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ruff
          fetch-depth: 0
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true
          version: "0.10.12"

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: "ruff"
          lookup-only: false

      - name: Install Rust toolchain
        run: rustup show

      - name: Compute diagnostic diff
        id: compute-diagnostic-diff
        shell: bash
        run: |
          cd ruff

          echo "Enabling configuration overloads (see .github/ty-ecosystem.toml)"
          mkdir -p ~/.config/ty
          cp .github/ty-ecosystem.toml ~/.config/ty/ty.toml

          echo "new commit"
          git checkout -b new_commit "$GITHUB_SHA"
          git rev-list --format=%s --max-count=1 new_commit
          cp crates/ty_python_semantic/resources/primer/good.txt projects_new.txt
          cp crates/ty_python_semantic/resources/primer/flaky.txt projects_flaky.txt

          echo "old commit (merge base)"
          MERGE_BASE="$(git merge-base "$GITHUB_SHA" "origin/$GITHUB_BASE_REF")"
          git checkout -b old_commit "$MERGE_BASE"
          git rev-list --format=%s --max-count=1 old_commit
          cp crates/ty_python_semantic/resources/primer/good.txt projects_old.txt

          cd ..

          uv tool install "git+https://github.com/astral-sh/ecosystem-analyzer@73fe4d9a7c940023ac2addc008097758c877b7ec"

          ecosystem-analyzer \
            --repository ruff \
            --flaky-runs 10 \
            diff \
            --profile=profiling \
            --projects-old ruff/projects_old.txt \
            --projects-new ruff/projects_new.txt \
            --projects-flaky ruff/projects_flaky.txt \
            --old old_commit \
            --new new_commit \
            --output-old diagnostics-old.json \
            --output-new diagnostics-new.json

          mkdir dist

          ecosystem-analyzer \
            generate-diff \
            diagnostics-old.json \
            diagnostics-new.json \
            --old-name "main (merge base)" \
            --new-name "$REF_NAME" \
            --output-html dist/diff.html

          set +e
          ecosystem-analyzer \
            generate-diff-statistics \
            diagnostics-old.json \
            diagnostics-new.json \
            --fail-on-new-abnormal-exits \
            --old-name "main (merge base)" \
            --new-name "$REF_NAME" \
            --output diff-statistics.md
          DIFF_STATISTICS_EXIT_CODE=$?
          set -e

          ecosystem-analyzer \
            generate-timing-diff \
            diagnostics-old.json \
            diagnostics-new.json \
            --old-name "main (merge base)" \
            --new-name "$REF_NAME" \
            --output-html dist/timing.html

          cat diff-statistics.md >> comment.md

          cat diff-statistics.md >> "$GITHUB_STEP_SUMMARY"

          echo "diff_statistics_exit_code=$DIFF_STATISTICS_EXIT_CODE" >> "$GITHUB_OUTPUT"

      # NOTE: astral-sh-bot uses this artifact to post comments on PRs.
      # Make sure to update the bot if you rename the artifact.
      - name: "Upload full report"
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: full-report
          path: dist/

      # NOTE: astral-sh-bot uses this artifact to post comments on PRs.
      # Make sure to update the bot if you rename the artifact.
      - name: Upload comment
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: comment.md
          path: comment.md

      - name: Upload diagnostics diff
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: diff.html
          path: dist/diff.html

      - name: Upload timing diff
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: timing.html
          path: dist/timing.html

      - name: Fail on new abnormal exits
        if: steps.compute-diagnostic-diff.outputs.diff_statistics_exit_code != '0'
        run: exit 1
