name: ty ecosystem-analyzer

permissions: {}

on:
  pull_request:
    paths:
      - "crates/ty*/**"
      - "!crates/ty_ide/**"
      - "!crates/ty_server/**"
      - "!crates/ty_test/**"
      - "!crates/ty_completion_eval/**"
      - "!crates/ty_wasm/**"
      - "crates/ruff_db"
      - "crates/ruff_python_ast"
      - "crates/ruff_python_parser"
      - ".github/workflows/ty-ecosystem-analyzer.yaml"
      - ".github/ty-ecosystem.toml"
      - "crates/ty_python_semantic/resources/primer/**"
      - "Cargo.lock"
      - "!**.md"
      - "!**.snap"
      # It's tempting to skip all Python files in every directory,
      # but changes to Python files in `ty_vendored` can affect the output of ecosystem analysis,
      # so we apply a narrow exemption for all files in the corpus directory instead.
      - "!crates/ty_python_semantic/resources/corpus/**"

concurrency:
  group: ty-ecosystem-analyzer-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1
  ECOSYSTEM_ANALYZER_COMMIT: 9fbc2accf946e230ac66182adf6599f559958d80

jobs:
  record-timestamp:
    name: Record timestamp
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: Record timestamp
        id: timestamp
        run: echo "timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_OUTPUT"

  analyze-branches:
    needs: [record-timestamp]
    strategy:
      matrix:
        branch: [base, PR]
    runs-on: ${{ github.repository == 'astral-sh/ruff' && 'depot-ubuntu-22.04-32' || 'ubuntu-latest' }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ruff
          fetch-depth: ${{ matrix.branch == 'PR' && 1 || 0 }}
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true
          version: "0.11.6"

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: "ruff"
          lookup-only: false

      - name: Install Rust toolchain
        run: rustup show

      - name: Setup configuration overrides
        working-directory: ruff
        shell: bash
        run: |
          echo "Enabling configuration overrides (see .github/ty-ecosystem.toml)"
          mkdir -p ~/.config/ty
          cp .github/ty-ecosystem.toml ~/.config/ty/ty.toml

          # If we're testing the merge base, make sure to still use the flaky list from the PR branch
          cp crates/ty_python_semantic/resources/primer/flaky.txt projects_flaky.txt

      - name: Setup merge base
        if: ${{ matrix.branch == 'base' }}
        working-directory: ruff
        shell: bash
        run: |
          echo "old commit (merge base)"
          MERGE_BASE="$(git merge-base "${GITHUB_SHA}" "origin/${GITHUB_BASE_REF}")"
          git checkout -b old_commit "${MERGE_BASE}"
          git rev-list --format=%s --max-count=1 old_commit
          cp crates/ty_python_semantic/resources/primer/good.txt projects.txt
          echo "COMMIT_TO_TEST=$MERGE_BASE" >> "$GITHUB_ENV"

      - name: Setup PR branch
        if: ${{ matrix.branch == 'PR' }}
        working-directory: ruff
        shell: bash
        run: |
          echo "new commit"
          git checkout -b new_commit "${GITHUB_SHA}"
          git rev-list --format=%s --max-count=1 new_commit
          cp crates/ty_python_semantic/resources/primer/good.txt projects.txt
          echo "COMMIT_TO_TEST=$GITHUB_SHA" >> "$GITHUB_ENV"

      - name: Analyze ${{ matrix.branch }} branch
        shell: bash
        env:
          BRANCH: ${{ matrix.branch }}
          EXCLUDE_NEWER: ${{ needs.record-timestamp.outputs.timestamp }}
        run: |
          uv tool install "git+https://github.com/astral-sh/ecosystem-analyzer@$ECOSYSTEM_ANALYZER_COMMIT"

          ecosystem-analyzer \
            --repository ruff \
            --flaky-runs 10 \
            analyze \
            --profile=profiling \
            --commit "${COMMIT_TO_TEST}" \
            --projects ruff/projects.txt \
            --projects-flaky ruff/projects_flaky.txt \
            --exclude-newer "${EXCLUDE_NEWER}" \
            --output "diagnostics-${BRANCH}.json"

      - name: Upload base diagnostics
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: diagnostics-${{ matrix.branch }}
          path: diagnostics-${{ matrix.branch }}.json

  generate-report:
    name: Generate diagnostic diff report
    needs: [analyze-branches]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true
          version: "0.11.6"

      - name: Download base diagnostics
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: diagnostics-base

      - name: Download PR diagnostics
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: diagnostics-PR

      - name: Generate reports
        id: generate-reports
        shell: bash
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          uv tool install "git+https://github.com/astral-sh/ecosystem-analyzer@$ECOSYSTEM_ANALYZER_COMMIT"

          mkdir dist

          ecosystem-analyzer \
            generate-diff \
            diagnostics-base.json \
            diagnostics-PR.json \
            --old-name "main (merge base)" \
            --new-name "$REF_NAME" \
            --output-html dist/diff.html

          set +e
          ecosystem-analyzer \
            generate-diff-statistics \
            diagnostics-base.json \
            diagnostics-PR.json \
            --fail-on-new-abnormal-exits \
            --old-name "main (merge base)" \
            --new-name "$REF_NAME" \
            --output diff-statistics.md
          DIFF_STATISTICS_EXIT_CODE=$?
          set -e

          ecosystem-analyzer \
            generate-timing-diff \
            diagnostics-base.json \
            diagnostics-PR.json \
            --old-name "main (merge base)" \
            --new-name "$REF_NAME" \
            --output-html dist/timing.html

          cat diff-statistics.md >> comment.md

          cat diff-statistics.md >> "$GITHUB_STEP_SUMMARY"

          echo "diff_statistics_exit_code=$DIFF_STATISTICS_EXIT_CODE" >> "$GITHUB_OUTPUT"

      # NOTE: astral-sh-bot uses this artifact to post comments on PRs.
      # Make sure to update the bot if you rename the artifact.
      - name: "Upload full report"
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: full-report
          path: dist/

      # NOTE: astral-sh-bot uses this artifact to post comments on PRs.
      # Make sure to update the bot if you rename the artifact.
      - name: Upload comment
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: comment.md
          path: comment.md

      - name: Upload diagnostics diff
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: diff.html
          path: dist/diff.html

      - name: Upload timing diff
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: timing.html
          path: dist/timing.html

      - name: Fail on new abnormal exits
        if: steps.generate-reports.outputs.diff_statistics_exit_code != '0'
        run: exit 1
